name: Cross

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: "foo"
    - name: install toolchain
      run: |
        sudo apt install -y g++-mingw-w64-x86-64
        rustup target add x86_64-pc-windows-gnu
    - name: Build native
      run: cargo build --release -vv
      working-directory: ./foo
    - name: Build windows
      run: cargo build --release --target x86_64-pc-windows-gnu -vv
      working-directory: ./foo
