name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup tools
      run: |
        rustup target add wasm32-unknown-unknown
        cargo install trunk
    - name: Build
      run: |
        trunk build --release --public-url learning-github
        cp -r ./dist/ ../public/
      working-directory: ./learning-yew
    - name: gh-pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        
