name: Rust

on:
  push:
    branches: [ disabled ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Setup tools
      run: |
        rustup target add wasm32-unknown-unknown
        cargo install trunk
    - name: Build
      run: |
        trunk build --release --public-url learning-github
        cp -r ./dist/ ../public/
      working-directory: ./learning-yew
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
