name: test

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: test-ubuntu
          - os: windows-latest
            target: test-windows
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo ${{ matrix.os }} > out.txt
    - name: Yet Another Upload Release Asset Action
      uses: shogo82148/actions-upload-release-asset@v1.6.2
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: out.txt
