name: test

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: test-ubuntu
          - os: windows-latest
            target: test-windows
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo ${{ matrix.os }} > out.txt
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ matrix.os }} # optional, default is artifact
        path: out.txt

      
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: ubuntu-latest
        path: ubuntu.txt
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: windows-latest
        path: windows.txt
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ github.ref }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: true
    - name: Yet Another Upload Release Asset Action
      uses: shogo82148/actions-upload-release-asset@v1.6.2
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "*"
